package org.romeo.headhounterclient.main.fragments.vacancies.favorites

import org.romeo.headhounterclient.main.fragments.vacancies.AbstractVacanciesPresenter
import org.romeo.headhounterclient.navigation.BackPressedListener

interface IVacanciesFavoritesPresenter : AbstractVacanciesPresenter, BackPressedListener